services:
  dis-design-system-go:
    x-repo-url: "https://github.com/ONSdigital/dis-design-system-go"
    build:
      context: ${DP_REPO_DIR:-../../../..}/dis-design-system-go
      dockerfile: Dockerfile.local
    volumes:
      - ${DP_REPO_DIR:-../../../..}/dis-design-system-go:/dis-design-system-go
    expose:
      - "9002"
    ports:
      - 9002:9002
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost:9002"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
